name: Build & Push Docker Image (manual, x86 only)

on:
  workflow_dispatch: {}      # 🚀 manual trigger only (no auto on push/pr)

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and push image to GitHub Container Registry (x86_64)

    permissions:
      contents: read
      packages: write          # needed to push to ghcr.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (linux/amd64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          # ghcr.io/<OWNER>/<IMAGE_NAME>:<TAG>
          tags: ghcr.io/${{ github.repository_owner }}/texicode:latest