name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for release (e.g., v1.0.0)'
        required: true
        default: 'v0.1.0'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: arm64
          - os: windows-latest
            arch: x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: ${{ matrix.arch }}

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
        shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}

      - name: Build executable
        run: pyinstaller --onefile ./src/main.py --name txr
        shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}

      - name: Rename artifact
        run: |
          if ($env:RUNNER_OS -eq "Windows") {
            Rename-Item "dist\txr.exe" "txr-${{ matrix.os }}-${{ matrix.arch }}.exe"
          } else {
            mv dist/txr "txr-${{ matrix.os }}-${{ matrix.arch }}"
          }
        shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}

      - name: Create Release (if not exists)
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ runner.os == 'Windows' && 'txr-${{ matrix.os }}-${{ matrix.arch }}.exe' || 'txr-${{ matrix.os }}-${{ matrix.arch }}' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
