name: Build and Release

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux supports x64 and ARM64
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-latest
            arch: arm64

          # macOS: x64 (Intel) and ARM64 (Apple Silicon / M1-M4)
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: arm64

          # Windows: only x64 is supported
          - os: windows-latest
            arch: x64

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: ${{ matrix.arch }}

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile ./src/main.py --name txr
        shell: bash

      - name: Rename artifact
        run: |
          OS="${{ matrix.os }}"
          ARCH="${{ matrix.arch }}"
          FILE_NAME="txr-${OS}-${ARCH}${{ runner.os == 'Windows' && '.exe' || '' }}"
          mv dist/txr $FILE_NAME || mv dist/txr.exe $FILE_NAME
        shell: bash

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: "txr-${{ matrix.os }}-${{ matrix.arch }}*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
