name: Build and Release

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: ${{ matrix.arch }}

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile ./src/main.py --name txr
        shell: bash

      - name: Rename artifact
        run: mv dist/txr txr-linux-${{ matrix.arch }}
        shell: bash

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: "txr-linux-${{ matrix.arch }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: ${{ matrix.arch }}

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile ./src/main.py --name txr
        shell: bash

      - name: Rename artifact
        run: mv dist/txr txr-macos-${{ matrix.arch }}
        shell: bash

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: "txr-macos-${{ matrix.arch }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: ${{ matrix.arch }}

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
        shell: pwsh

      - name: Build executable
        run: pyinstaller --onefile ./src/main.py --name txr
        shell: pwsh

      - name: Rename artifact
        run: Rename-Item "dist\txr.exe" "txr-windows-${{ matrix.arch }}.exe"
        shell: pwsh

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: "txr-windows-${{ matrix.arch }}.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
